/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aco;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Toolkit;
import java.awt.geom.AffineTransform;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author bishu
 */
public class CircleScrollable extends javax.swing.JFrame {

    /**
     * Creates new form test
     */
    public CircleScrollable(CirclePane CP) {
        initComponents(CP);
        CP.setPreferredSize(new Dimension(1000, CP.n*70));
        ImageIcon icon = new ImageIcon(System.getProperty("user.dir")+"\\src\\icons\\folder.jpg");
        setIconImage(icon.getImage());
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
        setTitle("CFG");
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents(CirclePane CirclePanel) {
        JScrollPane scroll = new javax.swing.JScrollPane(CirclePanel);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 1006, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
    }// </jeditor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            System.err.println(ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CircleScrollable(new CirclePane()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    // End of variables declaration                   
}

class CirclePane extends JPanel {

    public class coor {

        int x, y, n;

        public coor() {
            x = y = n = 0;
        }
    }

    public CirclePane() {
        setPreferredSize(new Dimension(1000, 2500));
        setBackground(Color.white);
    }

    public int m[][] = new int[100][100], n, i = 1, f[], j, k;
    public coor c[];
    public String pr = "";

    public String inc() {
        String s = "";
        s += k;
        k++;
        return s;
    }

    public String inc2(int J) {
        String s = "";
        s += J;
        return s;
    }
    
    public void drawCircle(Graphics g, int x, int y, int r, String s) {
        if (s.length() == 1) {
            g.drawString(s, x - 3, y + 4);
        } else {
            g.drawString(s, x - 6, y + 4);
        }
        g.drawOval(x - r, y - r, r * 2, r * 2);
    }

    public void drawArrow(Graphics g1, int x, int y, int xx, int yy) {
        Graphics2D g = (Graphics2D) g1.create();
        double dx = xx - x, dy = yy - y;
        double a = Math.atan2(dy, dx);
        int len = (int) Math.sqrt(dx * dx + dy * dy);
        AffineTransform at = AffineTransform.getTranslateInstance(x, y);
        at.concatenate(AffineTransform.getRotateInstance(a));
        g.transform(at);
        g.drawLine(0, 0, len, 0);
        g.fillPolygon(new int[]{len, len - 4, len - 4, len},
                new int[]{0, -4, 4, 0}, 4);
    }

    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        int x = getWidth() / 2; //System.out.println("x="+x+" n="+n);
        drawCircle(g, x, 30, 13, "0"); //center(x,30) r=13
        drawArrow(g, x, 43, x, 100 - 13);
        //drawCircle(g, x, 100, 13, "1");
        make(g);
        func(g, 0, 1, 0, getWidth(), 100);
        //repaint();
        //drawCircle(g, x, 100, 13, inc());
        //g.drawLine(x, 30+13, x, 100-13);
    }

    public void func(Graphics g, int I, int J, int xst, int xend, int y) {
        try {
            //super.paintComponent(g);
            //int d: 0=mid, 1=right, 2=left.
            int sm = 0, mid = (xend - xst) / 2;

            if (J == n - 1) {
                drawCircle(g, xst + mid, y, 13, inc2(J));
                return;
            }

            for (i = 0; i < n; i++) {
                sm += m[J][i];
            }
            //System.out.print("(i, j)= ("+I+", "+J+")  (xst, mid, xend, y)=("+xst+", "+mid+", "+xend+", "+y+") sm="+sm);
            if (sm == 0) {
                return;
            }
            //System.out.println(" circle "+J);

            drawCircle(g, xst + mid, y, 13, inc2(J));
            c[J].x = xst + mid;

            switch (sm) {
                case 1:
                    j = getIndex(J, 1);// System.out.println(" circle "+j);//": (x, y)=("+mid+", "+y+") (i, j)=("+I+", "+J+")");
                    // drawCircle(g, mid, y, 13, inc2(j));
                    if (j < J) { //System.out.println(J+" "+j);
                        drawArrow(g, c[J].x - 3, c[J].y - 13, c[j].x - 13, c[j].y + 5);
                    } else {
                        drawArrow(g, xst + mid + 3, y + 13, xst + mid + 3, y + 70 - 13);
                        func(g, J, j, xst, xend, y + 70);
                    }
                    break;
                case 2:
                    drawArrow(g, xst + mid + 3, y + 13, xst + (mid / 2) + 3, y + 70 - 13);
                    j = getIndex(J, 1);// System.out.println("Circle "+j);//+": (x, y)=("+mid+", "+y+") (i, j)=("+I+", "+J+")");
                    //drawCircle(g, mid, y, 13, inc2(j));
                    func(g, J, j, xst, xst + mid, y + 70);

                    drawArrow(g, xst + mid + 3, y + 13, xend - (mid / 2) + 3, y + 70 - 13);
                    j = getIndex(J, 2); //System.out.println("Circle "+j);//+": (x, y)=("+mid+", "+y+") (i, j)=("+I+", "+J+")");
                    //drawCircle(g, mid, y, 13, inc2(j));
                    func(g, J, j, xst + mid, xend, y + 70);
                    break;
            }
            if (sm > 2) {
                int xm = (xend - xst) / sm;
                for (int v = 1; v <= sm; v++) {
                    drawArrow(g, xst + mid + 3, y + 13, xst + (v - 1) * xm + (xm / 2) + 3, y + 70 - 13);
                    j = getIndex(J, v); //System.out.println("j="+j);
                    drawCircle(g, xst + (v - 1) * xm + (xm / 2) + 3, y + 70, 13, inc2(j));
                    drawArrow(g, xst + (v - 1) * xm + (xm / 2) + 3, y + 83, xst + mid + (v - 2), y + 140 - 13);
                }

                j = getIndex(j, 1);
                func(g, J, j, xst, xend, y + 140);
            }

            return;
        } catch (Exception e) {
            System.out.println("in func" + e);
        }
    }

    public int getIndex(int I, int s) {
        int sm = 0;
        for (int a = 0; a < n; a++) {
            sm += m[I][a];
            if (m[I][a] == 1 && sm == s) {
                return a;
            }
        }
        return 0;
    }

    public void make(Graphics g) {
        int i, j, x = getWidth() / 2;
        c = new coor[n];
        //f= new int[n];
        c[0] = new coor();
        c[0].x = x;
        c[0].y = 30;
        //f[0]=1;
        for (i = 1; i < n; i++) {
            c[i] = new coor();
            c[i].x = x;
            c[i].n = i;
            // f[i]=0;
            //for(j=0; j<n; j++)
            //f[i]+=m[i][j];
        }

        for (i = 0; i < n; i++) {
            for (j = 0; j < n; j++) {
                if (m[i][j] == 1 && c[j].y == 0) {
                    c[j].y = c[i].y + 70;
                }
            }
        }

        /*func2(g, 1, 0, getWidth());
         System.out.println("\nActual:");
         for(i=0; i<n; i++)
         { System.out.println(c[i].n+": "+c[i].x+", "+c[i].y);
         }
         /*        
         coor temp= new coor();
         for(i=0; i<n; i++)
         { for(j=0; j<n; j++)
         {
         if(c[i].y<c[j].y)
         {   temp=c[i]; c[i]=c[j];
         c[j]=temp;              
         }
         }
         }
         for(i=0; i<n; i++)
         { for(j=0; j<n; j++)
         {
         if(c[i].y==c[j].y && c[i].n<c[j].n)
         {   temp=c[i]; c[i]=c[j];
         c[j]=temp;              
         }
         }
         }
        
         for(i=0; i<n-1; i++)
         {  xm=x/f[i]; y=1;
         for(j=0; j<n; j++)
         {   if(m[i][j]==1)
         { c[j].x=y*xm; y+=2;  }
         }
         }
       
         /* for(i=0; i<n; i++)
         {  drawCircle(g, c[i].x, c[i].y, 13, inc2(c[i].n));
         System.out.println(c[i].n+": "+c[i].x+", "+c[i].y);
         } */
    }

    public void func2(Graphics g, int J, int xst, int xend) {
        try {
            int sm = 0, mid = (xend - xst) / 2, l;

            for (i = 0; i < n; i++) {
                sm += m[J][i];
            }

            if (sm == 1) {
                drawCircle(g, xst + mid, c[J].y, 13, inc2(c[J].n));
                System.out.println(c[J].n + ": " + c[J].x + ", " + c[J].y + " returned!");
                j = getIndex(J, 1);
                //drawArrow(g, xst+mid+3, c[J].y+13, xst+mid+3, c[j].y-13); 
                func2(g, j, xst, xend);
                return;
            }

            drawCircle(g, xst + mid, c[J].y, 13, inc2(c[J].n));
            //System.out.println(c[J].n+": "+c[J].x+", "+c[J].y);

            switch (sm) {
                case 1:
                    j = getIndex(J, 1);
                    drawArrow(g, xst + mid + 3, c[J].y + 13, xst + mid + 3, c[j].y - 13);
                    func2(g, j, xst, xend);
                    break;
                case 2:
                    k = getIndex(J, 1);
                    drawArrow(g, xst + mid + 3, c[J].y + 13, xst + (mid / 2) + 3, c[j].y - 13);
                    func2(g, k, xst, xst + mid);

                    j = getIndex(J, 2);
                    l = j;
                    func2(g, j, xst + mid, xend);
                    drawArrow(g, xst + mid + 3, c[k].y + 13, xend - (mid / 2) + 3, c[j].y - 13);
                    drawArrow(g, xst + mid + 3, c[l].y + 13, xend - (mid / 2) + 3, c[j].y - 13);

                    break;
            }
            if (sm > 2) {
                int xm = (xend - xst) / sm;
                for (int v = 1; v <= sm; v++) {
                    drawArrow(g, xst + mid + 3, c[J].y + 13, xst + (v - 1) * xm + (xm / 2) + 3, c[j].y - 13);
                    j = getIndex(J, v); //System.out.println("j="+j);
                    drawCircle(g, xst + (v - 1) * xm + (xm / 2) + 3, c[J].y + 70, 13, inc2(c[j].n));
                    drawArrow(g, xst + (v - 1) * xm + (xm / 2) + 3, c[J].y + 83, xst + mid + (v - 2), c[J].y + 140 - 13);
                }

                j = getIndex(j, 1);
                func2(g, j, xst, xend);
            }

            return;
        } catch (Exception e) {
            System.out.println("in func" + e);
        }
    }

}
